### ISSUE TITLE
react-query의 useQuery 리턴 객체를 객체구조분해할당하지 않고 쓰는 방식은 어떨까요? 저는 이렇게 쓰는데 다른 분들의 생각이 궁금해요

### ISSUE THREAD

**Issue by manudeli** [Bamdoliro/marururu#105]
@ChanhyukPark-Tech 찬혁님, 객체구조분해할당하지 않고 쓰는 방식은 어떨까요? 저는 이렇게 쓰는데 다른 분들의 생각이 궁금해요

1. 객체의 필드를 사용하는 방식으로 쓰면 변수를 rename하지 않고도 객체를 기준으로 모아서 생각할 수 있다고 생각해요.
2. 새 필드를 사용해야하는 경우나 삭제하는 경우 변경에 유연해요. (아래 코드에 설명)
```tsx
const faqListQuery = useFaqListQuery();

faqListQuery.data
faqListQuery.isLoading // 이와 같이 다른 필드가 추가되야 할때 위에 변수 선언하는 라인의 변경이 없이 필드만 사용하면 됨
faqListQuery.isSuccess // 동일한 설명
```

cc. @SEOKKAMONI

_Originally posted by @manudeli in https://github.com/Bamdoliro/marururu/pull/84#discussion_r1241018111_

**Comment by ChanhyukPark-Tech** [comment]
하나하나씩 다 빼지않고 객체 하나로 반환해주는 종현님의 의견이 더 좋아보이네요! 1번과 2번 이유 모두 동의합니다!😄

제 생각에 구조분해할당해서 가져올때 이점은 useFaqListQuery가 useQuery의 반환값을 전부 리턴하는것이 아닌 특정값만 뱉어줄때 유리할것 같아요. (지금 marumaru의 경우 훅에서 data만 뱉어줌) => 훅의 역할은 data를 반환하는것으로 제한


### A
```tsx
export const useFaqListQuery = () => {
  const { data } = useQuery<FaqListType[]>([KEY.FAQ_LIST], () => faqList());
  return { data: data || [] };  // 특정값만 뱉어줌
};
```

### B
```tsx
export const useFaqListQuery = () => {
  return useQuery<FaqListType[]>([KEY.FAQ_LIST], () => faqList());
};
```

A의경우 가져올때 객체구조분해할당을 해서 가져오는게 좋을 것 같고,(훅의 반환값의 인터페이스가 이미 정해져있으므로)
B의경우 종현님 말씀처럼 언제 어디서나 변경이 유연하도록 구조분해할당을 하지 않는것이 좋을 것 같네요~!

무엇보다 팀의 컨벤션에 따르는것이 중요할 것 같긴하네요 🥳

종현님 덕분에 새로운 시각을 얻었습니다~~!~!

**Comment by manudeli** [comment]
> ```tsx
> export const useFaqListQuery = () => {
>   const { data } = useQuery<FaqListType[]>([KEY.FAQ_LIST], () => faqList());
>   return { data: data || [] };  // 특정값만 뱉어줌
> };
> ```

이 경우에는 [useQuery의 initialData](https://tanstack.com/query/v4/docs/react/guides/initial-query-data)를 활용하면 어떨까요?
data의 타입을 보장하기 위해서라면 이렇게도 보장할 수 있을 거 같아요.
![image](https://github.com/Bamdoliro/marururu/assets/61593290/e78a6309-ae89-4e30-9f50-d08a1a562992)

만약 아래와 같이 사용한다면 useFaqListQuery가 아니라 useFaqList가 되어야 한다고 생각해요. 이제 저 리턴 객체는 query가 아니라 새로 만든 객체니까요. 하지만 initialData로 보장한다면 useFaqListQuery를 유지할 수 있기 때문에 더 좋다고 생각해요.
```tsx
export const useFaqListQuery = () => {
  const { data } = useQuery<FaqListType[]>([KEY.FAQ_LIST], () => faqList());
  return { data: data || [] };  // 특정값만 뱉어줌
};
```

여러분은 어떻게 생각하시나요?

**Comment by SEOKKAMONI** [comment]
오 그러네요 오 저렇게하면 훨씬 간편하고 따로 data isLoading을 구조준햐할당하고 리턴하지않아도 마음대로 사용할수있겠네요 감사합니다 !! 이니셜데이터라는게 있었군요!! 바로 기숙사가서 적용하겠습니다 벙말 감사합니다 ㅜㅜ 종현님 코드 많이 참고했었는ㄷ.. 영광입니다

**Comment by SEOKKAMONI** [comment]
[리뷰를 반영한 PR](https://github.com/Bamdoliro/marururu/pull/107) 리뷰를 반영해보았습니다 시간 되시면 피드백 부탁드립니다 !!
