### ISSUE TITLE
apps/user/src/services/ 폴더에 QueryClientProvider.tsx 관련 질문

### ISSUE THREAD

**Issue by arkk200** [Bamdoliro/marururu#126]
### ❓궁금해요

QueryClientProvider.tsx 파일에 GlobalStyle 컴포넌트가 해당 파일에 역할과 어울리지 않다고 생각합니다.
저는 이 컴포넌트를 apps/user/src/app/layout.tsx 파일로 옮겨야 한다고 생각하는데 어떻게 생각하시나요?

**Comment by arkk200** [comment]
@SEOKKAMONI

**Comment by SEOKKAMONI** [comment]
layout에다가 옮기게되면 use client를 선언해야하고 use client를 선언하게된다면 metadata를 사용하지 못합니다 그래서 Provider에 묶어야했습니다 하지만 GlobalStyled 하나만을 위해서 Provider를 따로 만드는것은 비효율적이라 생각해서 QueryClientProvider에 같이 묶게되었습니다

**Comment by SEOKKAMONI** [comment]
GlobalStyled만을 위해 Provider를 판다면 너무 비효율적이라 생각해서 묶게된건데 명재님의 생각은 어떤지 궁금합니다

**Comment by arkk200** [comment]
이건 한 번 다른 사람에게 물어봐야할 것 같습니다
@manudeli

**Comment by SEOKKAMONI** [comment]
나중에 recoil을 사용하게되면 recoil root도 묶어줘야하게됩니다 그때 Provider를 분리하여 묶어주면 될것같습니다
