### ISSUE TITLE
app/user/components/ 폴더에 index.ts 파일을 추가해 간략화해야합니다.

### ISSUE THREAD

**Issue by arkk200** [Bamdoliro/marururu#130]
### ✨ 개요

packages/ 폴더처럼 해당 폴더에 index.ts 파일을 추가해 컴포넌트들을 한 파일로 묶어야 합니다.

### ✅ 해야 할 일

- [x] components/ 폴더에 index.ts 파일 추가해 컴포넌트 하나로 묶기

**Comment by SEOKKAMONI** [comment]
칸반에 안올리는 이유가 있나여

**Comment by arkk200** [comment]
깜빡했네요ㅋㅋ
