### ISSUE TITLE
원서접수 페이지에 하위 페이지 내 이동 시 이동 전 페이지의 데이터가 안보입니다.

### ISSUE THREAD

**Issue by arkk200** [Bamdoliro/marururu#184]
### 🐞설명

https://github.com/Bamdoliro/marururu/assets/102217839/5da5cc78-0b5d-47f8-9741-6731f0942523

위 영상처럼 페이지 이동하고 돌아와보면 데이터가 안보여요

### 🌏 환경

OS: macOS 13.4.1

**Comment by SEOKKAMONI** [comment]
확인 고치러 가보겠습니다

**Comment by SEOKKAMONI** [comment]
앗 명재님이 하시는건가요?

**Comment by arkk200** [comment]
네넵

**Comment by arkk200** [comment]
#178 머지 될때까지 기다리겠스비낟

**Comment by SEOKKAMONI** [comment]
넵 추천곡 있습니다

**Comment by SEOKKAMONI** [comment]
https://www.youtube.com/watch?v=JG2DqTNr4uA&list=RDJG2DqTNr4uA&start_radio=1 ㄱ ㄱ 캡좋아요

**Comment by arkk200** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
