### ISSUE TITLE
[개선] 1차 QA with 선아T, 정하T

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/marururu#379]
### ✨ 개요

.

### ✅ 해야 할 일

- [x] 신준서 님의 1차 합격을 기원합니다
- [x] 수학 모의성적 2배 확인
- [x] D-Day 컴포넌트 시간 추가 및 적절한 걸로 변경
- [x] title 변경
- [x] 전화번호 placeholder에 '-' 없이 해주세요 추가
- [x] 전화번호 숫자 제외 넣으면 씹기
- [x] 소년 소녀 가장 중간 구분점 넣기
- [x] 보호자관계 올리고 주소 내려
- [x] 생년월일 Input으로 변경
- [x] 깨지는 style 수정
- [x] 없음 -> - 로 바꾸기

### 🙋🏻 덧붙일 말

파이팅 ^^;

**Comment by SEOKKAMONI** [comment]
까이면서 눈물날뻔

**Comment by SEOKKAMONI** [comment]
까이면서 눈물날뻔

**Comment by huise0ng** [comment]
@SEOKKAMONI **화이팅** 하세용 !!
