### ISSUE TITLE
컴포넌트 비즈니스 로직 분리

### ISSUE THREAD

**Issue by SEOKKAMONI** [Bamdoliro/marururu#433]
### ✨ 개요

현재 페이지 파일만 비즈니스 로직을 분리하고 있습니다 하지만 한 파일에 너무 많은 양의 코드가 있어 읽기 어려우며 비즈니스 로직도 파악이 어려워져 컴포넌트 파일도 비즈니스 로직을 분리해야합니다

### ✅ 해야 할 일

- [ ] 컴포넌트 비즈니스 로직 분리

**Comment by huise0ng** [comment]
@SEOKKAMONI 거의 다되어가네용ㅎㅎ 
좀만 더 힘내세요오!!
