### ISSUE TITLE
[admin] 어드민 로그인 페이지 리다이렉트 개발

### ISSUE THREAD

**Issue by arkk200** [Bamdoliro/marururu#465]
### ✨ 개요

어드민 페이지에 들어갔을 때 로그인 페이지로 바로 리다이렉트하는 기능을 추가해야합니다.

### ✅ 해야 할 일

- [ ] 어드민 로그인 페이지 리다이렉트 개발

**Comment by junghongseop** [comment]
어드민 페이지에 들어갔을 때 로그인 페이지로 바로 리다이렉트하는 기능을 추가하는 대신 어드민 접속시 바로 로그인 페이지가 뜨도록 수정하여 이 이슈를 닫도록 하겠습니다.
