### ISSUE TITLE
[user] 컴활 자격증을 한개만 선택 가능하도록 수정

### ISSUE THREAD

**Issue by junghongseop** [Bamdoliro/marururu#551]
### ✨ 개요

컴활 자격증은 한개만 선택 가능하도록 수정할려고 합니다.

### ✅ 해야 할 일

- [ ] 컴활 자격증 한개만 선택 가능하도록 수정

**Comment by MinjuN07** [comment]
컴퓨터 활용 등급 자격증은 2급,3급 둘 다 가지고 있을 수도 있어, 컴퓨터 활용 등급 자격증 분야 체크 박스를 여러 개 체크 할 수 있게 하되, 가장 높은 점수만 인정되도록 변경 하겠습니다. 그러므로 이슈를 닫겠습니다.
