### ISSUE TITLE
[기능] README.md 작성

### ISSUE THREAD

**Issue by ChanhyukPark-Tech** [Bamdoliro/marururu#98]
### ✨ 개요

프로젝트 전체의 README.md
- 모노레포 서비스별 README.md 에 각 프로젝트 및 서비스에 대한 설명 및 구조를 간단하게 적으며, 새롭게 합류할 팀원에게 좋은 온보딩 경험을 선사할 수 있다고 생각해요.
- 또한 깔끔한 README.md는 제 3자가 프로젝트를 봤을때 쉽게 구조를 파악하고 온보딩 할 수 있다고 생각해요
- 패키지의 목적, 폴더구조, 추구하는 방향성 등을 적으면 좋겠네요!

### ✅ 해야 할 일

- 프로젝트 전체 READMD.md파일 작성
- maru-theme READMD.md파일 작성
- maru-ui READMD.md파일 작성
- maru-util READMD.md파일 작성

### 🙋🏻 덧붙일 말

`실행 명령어?` 도 복잡하다면 적어두는게 좋을 것 같아요!

**Comment by SEOKKAMONI** [comment]
감사합니다 !!!!!!!
